version: "3"
networks:
   huawei-stay-connected-network:
services:
 mariadb:
  container_name: huaweimariadb
  tty: true
  image: mariadb
  ports: 
   - "3306:3306"
  networks:
   -  huawei-stay-connected-network
  volumes:
   - ./maria:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: 
   MYSQL_DATABASE: 
   MYSQL_USER: 
   MYSQL_PASSWORD: 
 php:
  container_name: php-huawei
  build: ./php
  ports:
   - "9000:9000"
  volumes:
   - ./src/:/var/www/html/
  networks:
   -  huawei-stay-connected-network
 web:
  container_name: huaweiweb
  image: nginx
  volumes:
   - ./src/:/var/www/html/
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  networks:
   -  huawei-stay-connected-network
  ports:
    - "86:80"
  depends_on:
    - php
